services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: crud_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "Your_strong_password123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=CrudAppDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"

volumes:
  mssqldata:
