version: "3.8"
services:
  approd:
    build:
      context: ./CrudApp
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:8080
      - 5001:8081
