monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    # utile pour capter les erreurs PHP/Symfony
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
