# Étape 1 : Build de l'application
FROM node:20 AS builder

WORKDIR /app

# Copier les fichiers de projet
COPY package*.json ./
COPY tsconfig.json ./
COPY svelte.config.js ./
COPY vite.config.ts ./
RUN npm install 

COPY . .

EXPOSE 5173

# Installer les dépendances
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

