# Étape 1 : Build de l'application
FROM node:20 AS builder

WORKDIR /app

# Copier les fichiers de projet
COPY package*.json ./
COPY tsconfig.json ./
COPY svelte.config.js ./
COPY vite.config.ts ./
COPY . .

# Installer les dépendances
RUN npm install

# Build de l'application
RUN npm run build

# Étape 2 : Serveur nginx pour la prod
FROM nginx:stable-alpine AS production

# Copier la configuration nginx
#COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers buildés
COPY --from=builder /app/dist /usr/share/nginx/html

# Exposer le port par défaut
EXPOSE 80

# Lancer nginx
CMD ["nginx", "-g", "daemon off;"]
